### ISSUE TITLE
rosbag2 cannot play back multiple compressed files

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#202] opened 2020-02-24 21:14 UTC
## Description

Fix the bug, detailed here https://github.com/ros2/rosbag2/issues/296, where multiple compressed files cannot be played back.

This is a tracking ticket.

## Expected Behavior
rosbag2 can play back multiple compressed files

## Actual Behavior
rosbag2 throws an exception and halts playback, see ros2/rosbag2#296 for details

## To Reproduce
See ros2/rosbag2#296 for details

## Screenshots
PROMPT: If applicable, add screenshots to help explain your problem.

## System (please complete the following information)
 - OS: Ubuntu 18.04
 - ROS2 Distro: master, building from source

**Comment by dabonnie** [comment] 2020-02-24 21:16
Potential fix in progress, needs tests added: https://github.com/ros2/rosbag2/issues/296

**Comment by thomas-moulard** [comment] 2020-02-28 21:35
Closing as duplicate of #192.

**Closed by thomas-moulard** 2020-02-28 21:35 UTC
Labels: bug
